apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temple-adventure.fullname" . }}-secrets
  labels:
    {{- include "temple-adventure.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ "temple-adventure-db-pass" | b64enc | quote }}
